// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmqUNM72bNecuRrUR5kBehXpmuuONu8E',
    appId: '1:341437966385:web:849690645ad9560782cd10',
    messagingSenderId: '341437966385',
    projectId: 'wrg-auto-2c95d',
    authDomain: 'wrg-auto-2c95d.firebaseapp.com',
    storageBucket: 'wrg-auto-2c95d.appspot.com',
    measurementId: 'G-QD8EDSG4GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GqiW_9wRKs8XIVcYYXssJbo3_oMKaWk',
    appId: '1:341437966385:android:c4320e4d2505d1c682cd10',
    messagingSenderId: '341437966385',
    projectId: 'wrg-auto-2c95d',
    storageBucket: 'wrg-auto-2c95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe0ZRlcQdMWRu4xMf85aLuSILo5ptFgqM',
    appId: '1:341437966385:ios:d9e71c7aeb7a0caf82cd10',
    messagingSenderId: '341437966385',
    projectId: 'wrg-auto-2c95d',
    storageBucket: 'wrg-auto-2c95d.appspot.com',
    androidClientId: '341437966385-8a5f0t5re0fis816ct3fi0td5qknsa18.apps.googleusercontent.com',
    iosClientId: '341437966385-eeo6v1f4eotei9qabmbg6fagk9htvqge.apps.googleusercontent.com',
    iosBundleId: 'com.fortech.wrg2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe0ZRlcQdMWRu4xMf85aLuSILo5ptFgqM',
    appId: '1:341437966385:ios:e8c58f624e5ff1b482cd10',
    messagingSenderId: '341437966385',
    projectId: 'wrg-auto-2c95d',
    storageBucket: 'wrg-auto-2c95d.appspot.com',
    androidClientId: '341437966385-8a5f0t5re0fis816ct3fi0td5qknsa18.apps.googleusercontent.com',
    iosClientId: '341437966385-ls8i5h9ohkmsqtd8vomrqqb25f4eeqcj.apps.googleusercontent.com',
    iosBundleId: 'com.fortech.wrg2.RunnerTests',
  );
}
